#!/bin/bash
DATA_ROOT="../../"
SAMPLE_VIEW_NUM=-1
SPEC_SAMPLE_NUM=32
DIFF_SAMPLE_NUM=8
THREAD_NUM=24
SERVER_NUM=1
WHICH_SERVER=0
IS_FOR_SERVER=true
IF_FIX_NORMAL=false
M_LEN_PERVIEW=3
TEX_RESOLUTION=512
python prepare_split.py $DATA_ROOT $DIFF_SAMPLE_NUM $SPEC_SAMPLE_NUM $SAMPLE_VIEW_NUM $THREAD_NUM $IS_FOR_SERVER $IF_FIX_NORMAL $M_LEN_PERVIEW $TEX_RESOLUTION $SERVER_NUM $WHICH_SERVER
#python split_data_and_prepare_for_server.py $DATA_ROOT $DIFF_SAMPLE_NUM $SPEC_SAMPLE_NUM $SAMPLE_VIEW_NUM $THREAD_NUM $IS_FOR_SERVER $IF_FIX_NORMAL $M_LEN_PERVIEW $TEX_RESOLUTION